### PR TITLE
Update batch xform example for SDKv2

### LINKED ISSUE #1600: Sample code not working in the environment where SDK >=2.0.0
# Problem

[Amazon SageMaker Batch Transform](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_batch_transform/introduction_to_batch_transform/batch_transform_pca_dbscan_movie_clusters.ipynb) does not work in the environment where SDK >=2.0.0.

Please provide workarounds.

# Error
```
ImportError                               Traceback (most recent call last)
<ipython-input-5-4d8117735119> in <module>
      2 import sagemaker
      3 import sagemaker.amazon.common as smac
----> 4 from sagemaker.amazon.amazon_estimator import get_image_uri
      5 from sagemaker.transformer import Transformer
      6 from sagemaker.predictor import csv_serializer, json_deserializer

ImportError: cannot import name 'get_image_uri' from 'sagemaker.amazon.amazon_estimator' (/opt/conda/lib/python3.7/site-packages/sagemaker/amazon/amazon_estimator.py)
```
```
ImportError                               Traceback (most recent call last)
<ipython-input-12-3ae6569f91f4> in <module>
      4 #from sagemaker.amazon.amazon_estimator import get_image_uri
      5 from sagemaker.transformer import Transformer
----> 6 from sagemaker.predictor import csv_serializer, json_deserializer
      7 import matplotlib.pyplot as plt
      8 import pandas as pd

ImportError: cannot import name 'csv_serializer' from 'sagemaker.predictor'
```

### PR DESCRIPTION
**Pull request by seanpmorgan**
Fixes #1600

*Description of changes:*
Uses SDKv2 `inputs.TrainingInput` instead of `s3_input`. Uses correct SM SDKv2 ser/de for deployment

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by seanpmorgan** [comment]
CI is failing for `FileNotFoundError: [Errno 2] No such file or directory: '/tmp/reviews/amazon_reviews_us_Digital_Video_Download_v1_00.tsv.gz` Not sure why the runner wouldn't download the data but I tested the notebook and it runs successfully

**Review by aaronmarkham — APPROVED** [review]
