### ISSUE TITLE
Sample code not working in the environment where SDK >=2.0.0

### ISSUE THREAD

**Issue by oonisim** [aws/amazon-sagemaker-examples#1600]
# Problem

[Amazon SageMaker Batch Transform](https://github.com/aws/amazon-sagemaker-examples/blob/master/sagemaker_batch_transform/introduction_to_batch_transform/batch_transform_pca_dbscan_movie_clusters.ipynb) does not work in the environment where SDK >=2.0.0.

Please provide workarounds.

# Error
```
ImportError                               Traceback (most recent call last)
<ipython-input-5-4d8117735119> in <module>
      2 import sagemaker
      3 import sagemaker.amazon.common as smac
----> 4 from sagemaker.amazon.amazon_estimator import get_image_uri
      5 from sagemaker.transformer import Transformer
      6 from sagemaker.predictor import csv_serializer, json_deserializer

ImportError: cannot import name 'get_image_uri' from 'sagemaker.amazon.amazon_estimator' (/opt/conda/lib/python3.7/site-packages/sagemaker/amazon/amazon_estimator.py)
```
```
ImportError                               Traceback (most recent call last)
<ipython-input-12-3ae6569f91f4> in <module>
      4 #from sagemaker.amazon.amazon_estimator import get_image_uri
      5 from sagemaker.transformer import Transformer
----> 6 from sagemaker.predictor import csv_serializer, json_deserializer
      7 import matplotlib.pyplot as plt
      8 import pandas as pd

ImportError: cannot import name 'csv_serializer' from 'sagemaker.predictor'
```

**Comment by oonisim** [comment]
If the SDK version is >=2.0.0 then the csv_serializer and the get_image_uri modules have been deprecated.

**Comment by IvyBazan** [comment]
The example notebooks do not currently support SageMaker Python SDK >=2.0.0. Because of this, we recommend that you pin your SDK version as follows:
`pip install --upgrade "sagemaker<2"`

Some notebooks will support SDK >=2.0.0 and  will have commands to upgrade and rollback the kernel built into the notebook.
