### ISSUE TITLE
Ray version 0.6.5 yields ImportError: cannot import name 'get_agent_class'

### ISSUE THREAD

**Issue by ChuaCheowHuan** [aws/amazon-sagemaker-examples#885]
Hi, 

I tried training a simple custom RL environment following the example in [rl_network_compression_ray_custom](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/reinforcement_learning/rl_network_compression_ray_custom) which uses ray 0.5.3. The training was successful. However, when I tried to use ray 0.6.5, the following error occurs:

```
algo-1-nj9pq_1  | Traceback (most recent call last):
algo-1-nj9pq_1  |   File "mod_op_train.py", line 12, in <module>
algo-1-nj9pq_1  |     from sagemaker_rl.ray_launcher import SageMakerRayLauncher
algo-1-nj9pq_1  |   File "/opt/ml/code/sagemaker_rl/ray_launcher.py", line 13, in <module>
algo-1-nj9pq_1  |     from ray.rllib.agents.agent import get_agent_class
algo-1-nj9pq_1  | ImportError: cannot import name 'get_agent_class'
```

The same error also occurred when I ran the [rl_network_compression_ray_custom](https://github.com/awslabs/amazon-sagemaker-examples/tree/master/reinforcement_learning/rl_network_compression_ray_custom) example using Ray 0.6.5.

I believe that both versions are officially supported by SageMaker. 

The only change I did was from `toolkit_version='0.5.3'` to `toolkit_version='0.6.5'` in the `RLEstimator` in the notebook file.

Is there any additional steps that I'm missing to make it work in version 0.6.5?
Is there any example that uses version 0.6.5?

Any pointers would be appreciated. Thank you.

**Comment by saurabh3949** [comment]
Yes, we are working on a fix. #886 
It will be committed soon. Thanks!

**Comment by ChuaCheowHuan** [comment]
Hi, the merge #886 did resolve the above mentioned issue. However, I got a `PermissionError: [Errno 13]` after `Reporting training SUCCESS` for my custom environment. 

```
algo-1-vmd10_1  | Saved TensorFlow serving model!
algo-1-vmd10_1  | 2019-09-30 07:55:03,775 sagemaker-containers INFO     Reporting training SUCCESS
tmp8z_8haic_algo-1-vmd10_1 exited with code 0
Aborting on container exit...
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
~/anaconda3/envs/tensorflow_p36/lib/python3.6/distutils/file_util.py in _copy_file_contents(src, dst, buffer_size)
     28         try:
---> 29             fsrc = open(src, 'rb')
     30         except OSError as e:

PermissionError: [Errno 13] Permission denied: '/tmp/tmp8z_8haic/algo-1-vmd10/output/intermediate/training/PPO_ArrivalSim-v0_0_2019-09-30_07-54-31mi7pqqk2/log_sync6vobqpa5.log'
```
The full output is available in this [gist](https://gist.github.com/ChuaCheowHuan/b6d903919547bc713aeaac97a7e1ead9). Is there anything that I might be missing?

Any pointers would be appreciated. Thank you for the quick response.

**Comment by hsl89** [comment]
Dear SageMaker Community,
                 In our attempts to provide this repository with a better level of support                 going forward, we’re closing issues that were opened prior to the v2 release of the SDK.                 This is because we believe that over time many of the issues                 posted were solved with the latest release or other recent changes to the repo.                 This will help us reallocate resources towards issues that are                more likely to still be relevant today.                Some of the issues experienced now can be resolved by referencing the                v2 guide: https://sagemaker.readthedocs.io/en/stable/v2.html                 In this guide, you can find simple solutions to common notebook errors,                 like the renaming of parameters and classes.                If you believe your issue is still ongoing and you have updated error                messaging or other info, please re-open it, and we investigate the issue.
                Best Regards,
                AWS SageMaker Team
